import { jsPDF } from 'jspdf';

export type PDFContext = {
  production: any;
  crew: any[];
  locations: any[];
  inventory: any[];
  preview?: boolean;
  weather?: { temp_high: number; temp_low: number; description: string; icon: string; precipitation: number; wind_speed?: number } | null;
  forecast?: { date: string; temp_high: number; temp_low: number; description: string; icon: string; precipitation: number }[];
  company?: any;
  stripboardScenes?: any[];
  characters?: any[];
  budgetLines?: any[];
  financeDocs?: any[];
};

export function createDoc(orientation: 'p' | 'l' = 'p'): jsPDF {
  return new jsPDF({ orientation, unit: 'mm', format: 'letter' });
}

export function header(doc: jsPDF, title: string, production: any, company?: any) {
  const pageW = doc.internal.pageSize.getWidth();
  const brandHex = company?.primary_color || '#141414';
  const r = parseInt(brandHex.slice(1,3),16)||20;
  const g = parseInt(brandHex.slice(3,5),16)||20;
  const b = parseInt(brandHex.slice(5,7),16)||20;
  doc.setFillColor(r, g, b);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(company?.name || 'PRO-LOGIC STUDIO', 10, 8);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(title.toUpperCase(), 10, 14);
  doc.setFontSize(9);
  doc.text(production.name, pageW - 10, 8, { align: 'right' });
  doc.text(`Client: ${production.client || ''}`, pageW - 10, 14, { align: 'right' });
  doc.setTextColor(0, 0, 0);
}

export function footer(doc: jsPDF) {
  const pages = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pages} | Generated by PRO-LOGIC Studio | ${new Date().toLocaleDateString()}`, pageW / 2, pageH - 8, { align: 'center' });
  }
  doc.setTextColor(0, 0, 0);
}

export function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  doc.text(text.toUpperCase(), 10, y);
  doc.setDrawColor(200, 200, 200);
  doc.line(10, y + 1, doc.internal.pageSize.getWidth() - 10, y + 1);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  return y + 6;
}

export function tableRow(
  doc: jsPDF,
  cols: string[],
  widths: number[],
  y: number,
  startX = 10,
  isHeader = false,
  shade = false
) {
  if (isHeader) {
    doc.setFillColor(240, 240, 240);
    const totalW = widths.reduce((a, b) => a + b, 0);
    doc.rect(startX, y - 4, totalW, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
  } else {
    if (shade) {
      doc.setFillColor(250, 250, 250);
      const totalW = widths.reduce((a, b) => a + b, 0);
      doc.rect(startX, y - 4, totalW, 6, 'F');
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
  }

  let x = startX;
  cols.forEach((col, i) => {
    doc.text(col, x + 2, y);
    x += widths[i];
  });
  doc.setFont('helvetica', 'normal');
  return y + 6;
}

export function save(doc: jsPDF, filename: string, preview = false): string | void {
  footer(doc);
  if (preview) return doc.output('datauristring');
  doc.save(filename);
}
