// Auto-generated from PRO_LOGIC_Production_Equipment_Database.xlsx
export interface CatalogItem {
  item_id: string;
  name: string;
  category: string;
  subcategory: string;
  brand: string;
  model: string;
  description?: string;
  production_use?: string;
  replacement_value_usd?: number;
  rental_day_rate_usd?: number;
  voltage?: string;
  wattage?: string;
  amperage?: string;
  power_connector?: string;
  battery_type?: string;
  weight_kg?: number;
  dimensions?: string;
  status: string;
  condition?: string;
  warehouse_location?: string;
  kit_name?: string;
  insurance_required?: boolean;
  maintenance_cycle_days?: number;
  source_url?: string;
  notes?: string;
  data_confidence?: string;
}

export const EQUIPMENT_CATALOG: CatalogItem[] = [
  {
    "item_id": "CAM0001",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+Alexa+35",
    "name": "ARRI Alexa 35",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "ARRI",
    "model": "Alexa 35",
    "description": "4.6K Super 35 cinema camera body",
    "production_use": "A-camera for commercials, cinema, high-end production",
    "replacement_value_usd": 82000,
    "rental_day_rate_usd": 1400,
    "voltage": "10.5-34 V DC",
    "wattage": "~90 W",
    "power_connector": "LEMO 8-pin",
    "battery_type": "B-Mount / 24V block",
    "weight_kg": 2.9,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.arri.com/en/camera-systems/cameras/alexa-35",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0002",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+Alexa+Mini+LF",
    "name": "ARRI Alexa Mini LF",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "ARRI",
    "model": "Alexa Mini LF",
    "description": "Large format compact cinema camera body",
    "production_use": "A-camera for commercials, features, high-end content",
    "replacement_value_usd": 65000,
    "rental_day_rate_usd": 1200,
    "voltage": "11-34 V DC",
    "wattage": "~65 W",
    "power_connector": "LEMO 8-pin",
    "battery_type": "V-Mount / Gold Mount / block",
    "weight_kg": 2.6,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.arri.com/en/camera-systems/cameras/alexa-mini-lf",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0003",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=RED+V-RAPTOR+8K+VV",
    "name": "RED V-RAPTOR 8K VV",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "RED",
    "model": "V-RAPTOR 8K VV",
    "description": "8K full-frame cinema camera",
    "production_use": "Commercials, music videos, cinema",
    "replacement_value_usd": 24500,
    "rental_day_rate_usd": 650,
    "voltage": "11.5-17 V DC",
    "wattage": "~60 W",
    "power_connector": "DC-IN / EXT",
    "battery_type": "V-Mount / Gold Mount",
    "weight_kg": 1.8,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.red.com/v-raptor",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0004",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Sony+VENICE+2+8K",
    "name": "Sony VENICE 2 8K",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "Sony",
    "model": "VENICE 2 8K",
    "description": "Full-frame digital cinema camera",
    "production_use": "Feature film and commercial camera package",
    "replacement_value_usd": 59000,
    "rental_day_rate_usd": 1000,
    "voltage": "22-32 V DC",
    "wattage": "~76 W",
    "power_connector": "XLR 4-pin / battery plate",
    "battery_type": "V-Mount / 24V block",
    "weight_kg": 4.3,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://pro.sony/ue_US/products/digital-cinema-cameras/venice-2",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0005",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Canon+EOS+C500+Mark+II",
    "name": "Canon EOS C500 Mark II",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "Canon",
    "model": "EOS C500 Mark II",
    "description": "5.9K full-frame cinema camera",
    "production_use": "Commercial, documentary, corporate production",
    "replacement_value_usd": 16000,
    "rental_day_rate_usd": 450,
    "voltage": "14.4 V DC",
    "wattage": "~25 W",
    "power_connector": "DC input",
    "battery_type": "BP-A series / V-Mount",
    "weight_kg": 1.8,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.usa.canon.com/shop/p/eos-c500-mark-ii",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0006",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Blackmagic+Design+URSA+Mini+Pro+12K",
    "name": "Blackmagic URSA Mini Pro 12K",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "Blackmagic Design",
    "model": "URSA Mini Pro 12K",
    "description": "12K Super 35 digital film camera",
    "production_use": "Commercial and studio production",
    "replacement_value_usd": 6400,
    "rental_day_rate_usd": 275,
    "voltage": "12-20 V DC",
    "wattage": "~60 W",
    "power_connector": "XLR 4-pin",
    "battery_type": "V-Mount / Gold Mount",
    "weight_kg": 2.55,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.blackmagicdesign.com/products/blackmagicursaminipro",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0007",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Sony+FX6",
    "name": "Sony FX6",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "Sony",
    "model": "FX6",
    "description": "Full-frame compact cinema camera",
    "production_use": "Run-and-gun, documentary, commercial B-camera",
    "replacement_value_usd": 6000,
    "rental_day_rate_usd": 250,
    "voltage": "19.5 V DC",
    "wattage": "~18 W",
    "power_connector": "DC input",
    "battery_type": "BP-U series",
    "weight_kg": 0.89,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://pro.sony/en_US/products/handheld-camcorders/ilme-fx6v",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0008",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Canon+EOS+C70",
    "name": "Canon EOS C70",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "Canon",
    "model": "EOS C70",
    "description": "RF mount Super 35 cinema camera",
    "production_use": "Documentary, commercial, handheld production",
    "replacement_value_usd": 5500,
    "rental_day_rate_usd": 225,
    "voltage": "7.2 V battery / DC adapter",
    "power_connector": "DC coupler",
    "battery_type": "BP-A series",
    "weight_kg": 1.17,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.usa.canon.com/shop/p/eos-c70",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0009",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Blackmagic+Design+Pocket+Cinema+Camera+6K+Pro",
    "name": "Blackmagic Pocket Cinema Camera 6K Pro",
    "category": "Camera",
    "subcategory": "Cinema Camera",
    "brand": "Blackmagic Design",
    "model": "Pocket Cinema Camera 6K Pro",
    "description": "6K Super 35 compact cinema camera",
    "production_use": "Independent commercials, social, B-camera",
    "replacement_value_usd": 2500,
    "rental_day_rate_usd": 125,
    "voltage": "12 V DC",
    "power_connector": "2-pin locking DC",
    "battery_type": "NP-F570 / external",
    "weight_kg": 1.24,
    "dimensions": "Body only varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "CAM0010",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=DJI+Ronin+4D+6K",
    "name": "DJI Ronin 4D 6K",
    "category": "Camera",
    "subcategory": "Stabilized Cinema Camera",
    "brand": "DJI",
    "model": "Ronin 4D 6K",
    "description": "Integrated 4-axis stabilized cinema camera system",
    "production_use": "Commercial motion shots, vehicle shots, gimbal work",
    "replacement_value_usd": 7200,
    "rental_day_rate_usd": 350,
    "voltage": "Battery system",
    "power_connector": "TB50 / external",
    "battery_type": "TB50",
    "weight_kg": 4.67,
    "dimensions": "System varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Main Warehouse",
    "kit_name": "Camera Bodies",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.dji.com/ronin-4d",
    "notes": "Verify current specs/value",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0011",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+Signature+Prime+35mm",
    "name": "ARRI Signature Prime 35mm",
    "category": "Lens",
    "subcategory": "Prime Lens",
    "brand": "ARRI",
    "model": "Signature Prime 35mm",
    "description": "Large format PL/LPL cinema prime lens",
    "production_use": "High-end commercial and feature lens",
    "replacement_value_usd": 28500,
    "rental_day_rate_usd": 350,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 2.1,
    "dimensions": "Lens size varies",
    "status": "Available",
    "condition": "Excellent",
    "warehouse_location": "Lens Room",
    "kit_name": "ARRI Signature Primes",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.arri.com/en/camera-systems/cine-lenses/signature-prime-lenses",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0012",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+Signature+Prime+50mm",
    "name": "ARRI Signature Prime 50mm",
    "category": "Lens",
    "subcategory": "Prime Lens",
    "brand": "ARRI",
    "model": "Signature Prime 50mm",
    "description": "Large format PL/LPL cinema prime lens",
    "production_use": "High-end commercial and feature lens",
    "replacement_value_usd": 28500,
    "rental_day_rate_usd": 350,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 2.1,
    "dimensions": "Lens size varies",
    "status": "Available",
    "condition": "Excellent",
    "warehouse_location": "Lens Room",
    "kit_name": "ARRI Signature Primes",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.arri.com/en/camera-systems/cine-lenses/signature-prime-lenses",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0013",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Cooke+S4%2Fi+25mm",
    "name": "Cooke S4/i 25mm",
    "category": "Lens",
    "subcategory": "Prime Lens",
    "brand": "Cooke",
    "model": "S4/i 25mm",
    "description": "PL mount cinema prime lens with /i metadata",
    "production_use": "Commercial, feature, narrative work",
    "replacement_value_usd": 17500,
    "rental_day_rate_usd": 250,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 1.8,
    "dimensions": "Lens size varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lens Room",
    "kit_name": "Cooke S4/i Set",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://cookeoptics.com/lens/s4-i/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0014",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Cooke+S4%2Fi+50mm",
    "name": "Cooke S4/i 50mm",
    "category": "Lens",
    "subcategory": "Prime Lens",
    "brand": "Cooke",
    "model": "S4/i 50mm",
    "description": "PL mount cinema prime lens with /i metadata",
    "production_use": "Commercial, feature, narrative work",
    "replacement_value_usd": 17500,
    "rental_day_rate_usd": 250,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 1.8,
    "dimensions": "Lens size varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lens Room",
    "kit_name": "Cooke S4/i Set",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://cookeoptics.com/lens/s4-i/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0015",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ZEISS+Supreme+Prime+29mm",
    "name": "ZEISS Supreme Prime 29mm",
    "category": "Lens",
    "subcategory": "Prime Lens",
    "brand": "ZEISS",
    "model": "Supreme Prime 29mm",
    "description": "Full-frame cinema prime lens",
    "production_use": "Commercial, feature, premium digital cinema",
    "replacement_value_usd": 22000,
    "rental_day_rate_usd": 300,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 1.5,
    "dimensions": "Lens size varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lens Room",
    "kit_name": "ZEISS Supreme Set",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.zeiss.com/consumer-products/int/cinematography/supreme-prime-lenses.html",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0016",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Angenieux+Optimo+24-290mm",
    "name": "Angenieux Optimo 24-290mm",
    "category": "Lens",
    "subcategory": "Zoom Lens",
    "brand": "Angenieux",
    "model": "Optimo 24-290mm",
    "description": "High-end PL mount cinema zoom lens",
    "production_use": "Commercial, sports, feature zoom work",
    "replacement_value_usd": 85000,
    "rental_day_rate_usd": 900,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 11,
    "dimensions": "Large cinema zoom",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lens Room",
    "kit_name": "Zooms",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.angenieux.com/collections/optimo/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0017",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Canon+CN-E+24mm+T1.5",
    "name": "Canon CN-E 24mm T1.5",
    "category": "Lens",
    "subcategory": "Prime Lens",
    "brand": "Canon",
    "model": "CN-E 24mm T1.5",
    "description": "Cinema prime lens",
    "production_use": "Commercial and corporate video",
    "replacement_value_usd": 3950,
    "rental_day_rate_usd": 125,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 1.2,
    "dimensions": "Lens size varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lens Room",
    "kit_name": "Canon CN-E Set",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.usa.canon.com/shop/cinema-lenses",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LEN0018",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Fujinon+Premista+28-100mm",
    "name": "Fujinon Premista 28-100mm",
    "category": "Lens",
    "subcategory": "Zoom Lens",
    "brand": "Fujinon",
    "model": "Premista 28-100mm",
    "description": "Large format cinema zoom lens",
    "production_use": "Commercial, studio, feature zoom work",
    "replacement_value_usd": 39000,
    "rental_day_rate_usd": 550,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 3.8,
    "dimensions": "Zoom lens",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lens Room",
    "kit_name": "Zooms",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.fujifilm.com/products/optical_devices/cine_lens/premista/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0019",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Aputure+LS+600d+Pro",
    "name": "Aputure LS 600d Pro",
    "category": "Lighting",
    "subcategory": "LED Daylight",
    "brand": "Aputure",
    "model": "LS 600d Pro",
    "description": "High-output daylight LED fixture",
    "production_use": "Key light, exterior fill, commercial lighting",
    "replacement_value_usd": 1890,
    "rental_day_rate_usd": 95,
    "voltage": "100-240 V AC / 48 V DC",
    "wattage": "720 W",
    "amperage": "~7.5 A at 120V",
    "power_connector": "AC power / 3-pin XLR",
    "battery_type": "V-Mount option",
    "weight_kg": 11,
    "dimensions": "Fixture varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "LED Daylight",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.aputure.com/products/ls-600d-pro/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0020",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Aputure+LS+600x+Pro",
    "name": "Aputure LS 600x Pro",
    "category": "Lighting",
    "subcategory": "LED Bi-Color",
    "brand": "Aputure",
    "model": "LS 600x Pro",
    "description": "High-output bi-color LED fixture",
    "production_use": "Key light, commercial, studio",
    "replacement_value_usd": 2190,
    "rental_day_rate_usd": 110,
    "voltage": "100-240 V AC / 48 V DC",
    "wattage": "720 W",
    "amperage": "~7.5 A at 120V",
    "power_connector": "AC power / 3-pin XLR",
    "battery_type": "V-Mount option",
    "weight_kg": 11,
    "dimensions": "Fixture varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "LED Bi-Color",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.aputure.com/products/ls-600x-pro/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0021",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+SkyPanel+S60-C",
    "name": "ARRI SkyPanel S60-C",
    "category": "Lighting",
    "subcategory": "RGB LED Panel",
    "brand": "ARRI",
    "model": "SkyPanel S60-C",
    "description": "Color-tunable soft LED panel",
    "production_use": "Soft key, color wash, studio/commercial",
    "replacement_value_usd": 6250,
    "rental_day_rate_usd": 250,
    "voltage": "100-240 V AC",
    "wattage": "420 W",
    "amperage": "~3.5 A at 120V",
    "power_connector": "PowerCON",
    "battery_type": "Optional battery",
    "weight_kg": 12.8,
    "dimensions": "645 x 300 x 133 mm",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "RGB Panels",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.arri.com/en/lighting/led/skypanel",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0022",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+SkyPanel+S120-C",
    "name": "ARRI SkyPanel S120-C",
    "category": "Lighting",
    "subcategory": "RGB LED Panel",
    "brand": "ARRI",
    "model": "SkyPanel S120-C",
    "description": "Large color-tunable soft LED panel",
    "production_use": "Large soft source, studio, commercial",
    "replacement_value_usd": 9500,
    "rental_day_rate_usd": 350,
    "voltage": "100-240 V AC",
    "wattage": "420 W",
    "amperage": "~3.5 A at 120V",
    "power_connector": "PowerCON",
    "battery_type": "Optional battery",
    "weight_kg": 17,
    "dimensions": "Large panel",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "RGB Panels",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.arri.com/en/lighting/led/skypanel",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0023",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+Orbiter",
    "name": "ARRI Orbiter",
    "category": "Lighting",
    "subcategory": "LED Open Face",
    "brand": "ARRI",
    "model": "Orbiter",
    "description": "High-end directional LED fixture",
    "production_use": "Key, projection, studio and location work",
    "replacement_value_usd": 7500,
    "rental_day_rate_usd": 275,
    "voltage": "100-260 V AC",
    "wattage": "500 W",
    "amperage": "~4.2 A at 120V",
    "power_connector": "PowerCON TRUE1",
    "battery_type": "Optional battery",
    "weight_kg": 11.7,
    "dimensions": "Fixture varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "ARRI LED",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.arri.com/en/lighting/led/orbiter",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0024",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Nanlite+Forza+500B+II",
    "name": "Nanlite Forza 500B II",
    "category": "Lighting",
    "subcategory": "LED Bi-Color",
    "brand": "Nanlite",
    "model": "Forza 500B II",
    "description": "Bi-color COB LED fixture",
    "production_use": "Commercial, interview, location lighting",
    "replacement_value_usd": 1699,
    "rental_day_rate_usd": 85,
    "voltage": "100-240 V AC",
    "wattage": "560 W",
    "amperage": "~4.7 A at 120V",
    "power_connector": "AC power",
    "battery_type": "V-Mount option",
    "weight_kg": 4.6,
    "dimensions": "Fixture varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "LED Bi-Color",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://nanliteus.com/collections/forza",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0025",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Litepanels+Gemini+2x1+Soft",
    "name": "Litepanels Gemini 2x1 Soft",
    "category": "Lighting",
    "subcategory": "RGB LED Panel",
    "brand": "Litepanels",
    "model": "Gemini 2x1 Soft",
    "description": "RGBWW soft LED panel",
    "production_use": "Studio, commercial, controlled environments",
    "replacement_value_usd": 5300,
    "rental_day_rate_usd": 200,
    "voltage": "100-240 V AC",
    "wattage": "325 W",
    "amperage": "~2.7 A at 120V",
    "power_connector": "XLR / AC",
    "battery_type": "Gold/V-Mount option",
    "weight_kg": 10.1,
    "dimensions": "2x1 panel",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "RGB Panels",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.litepanels.com/en/products/gemini/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0026",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Astera+Titan+Tube+Kit",
    "name": "Astera Titan Tube Kit",
    "category": "Lighting",
    "subcategory": "Tube LED",
    "brand": "Astera",
    "model": "Titan Tube Kit",
    "description": "Wireless RGB tube light kit",
    "production_use": "Music videos, practicals, commercial accent lighting",
    "replacement_value_usd": 4200,
    "rental_day_rate_usd": 180,
    "voltage": "Battery / charging case",
    "wattage": "72 W per tube",
    "power_connector": "Charging case",
    "battery_type": "Internal battery",
    "weight_kg": 1.35,
    "dimensions": "1035 mm tube",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "Tube Kits",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://astera-led.com/titan/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0027",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Kino+Flo+FreeStyle+31+LED",
    "name": "Kino Flo FreeStyle 31 LED",
    "category": "Lighting",
    "subcategory": "RGB LED Panel",
    "brand": "Kino Flo",
    "model": "FreeStyle 31 LED",
    "description": "RGBWW LED panel system",
    "production_use": "Soft source for interviews and sets",
    "replacement_value_usd": 3150,
    "rental_day_rate_usd": 150,
    "voltage": "100-240 V AC",
    "wattage": "150 W",
    "amperage": "~1.25 A at 120V",
    "power_connector": "AC",
    "battery_type": "Optional battery",
    "weight_kg": 5.9,
    "dimensions": "Panel varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Lighting Cage",
    "kit_name": "RGB Panels",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://kinoflo.com/freestyle-led/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "LGT0028",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Mole-Richardson+2K+Fresnel",
    "name": "Mole-Richardson 2K Fresnel",
    "category": "Lighting",
    "subcategory": "Tungsten Fresnel",
    "brand": "Mole-Richardson",
    "model": "2K Fresnel",
    "description": "Traditional 2000W tungsten fresnel",
    "production_use": "Classic film lighting, warm hard source",
    "replacement_value_usd": 1800,
    "rental_day_rate_usd": 75,
    "voltage": "120 V AC",
    "wattage": "2000 W",
    "amperage": "16.7 A",
    "power_connector": "Edison / stage pin",
    "battery_type": "N/A",
    "weight_kg": 8,
    "dimensions": "Fixture varies",
    "status": "Available",
    "condition": "Fair",
    "warehouse_location": "Lighting Cage",
    "kit_name": "Tungsten",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://mole.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0029",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Sound+Devices+833",
    "name": "Sound Devices 833",
    "category": "Audio",
    "subcategory": "Field Recorder",
    "brand": "Sound Devices",
    "model": "833",
    "description": "Professional compact 8-series audio recorder",
    "production_use": "Location sound mixing and recording",
    "replacement_value_usd": 4500,
    "rental_day_rate_usd": 175,
    "voltage": "10-18 V DC",
    "wattage": "~20 W",
    "power_connector": "Hirose 4-pin / TA4",
    "battery_type": "L-Mount / external",
    "weight_kg": 1.3,
    "dimensions": "Recorder varies",
    "status": "Available",
    "condition": "Excellent",
    "warehouse_location": "Audio Cage",
    "kit_name": "Recorders",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.sounddevices.com/product/833/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0030",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Sound+Devices+MixPre-10+II",
    "name": "Sound Devices MixPre-10 II",
    "category": "Audio",
    "subcategory": "Field Recorder",
    "brand": "Sound Devices",
    "model": "MixPre-10 II",
    "description": "Portable multitrack audio recorder",
    "production_use": "Small crew location sound, interviews",
    "replacement_value_usd": 1775,
    "rental_day_rate_usd": 85,
    "voltage": "USB-C / 10-18 V DC",
    "power_connector": "USB-C / Hirose",
    "battery_type": "AA / L-Mount / external",
    "weight_kg": 0.91,
    "dimensions": "Recorder varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Recorders",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.sounddevices.com/product/mixpre-10-ii/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0031",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Sennheiser+MKH+416",
    "name": "Sennheiser MKH 416",
    "category": "Audio",
    "subcategory": "Shotgun Microphone",
    "brand": "Sennheiser",
    "model": "MKH 416",
    "description": "Industry-standard short shotgun microphone",
    "production_use": "Boom mic for dialogue, voiceover, field production",
    "replacement_value_usd": 999,
    "rental_day_rate_usd": 45,
    "voltage": "48 V phantom",
    "power_connector": "XLR",
    "battery_type": "N/A",
    "weight_kg": 0.175,
    "dimensions": "250 mm",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Shotgun Mics",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.sennheiser.com/en-us/catalog/products/microphones/mkh-416-p48u3/mkh-416-p48u3-001511",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0032",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Schoeps+CMC641",
    "name": "Schoeps CMC641",
    "category": "Audio",
    "subcategory": "Microphone",
    "brand": "Schoeps",
    "model": "CMC641",
    "description": "Supercardioid condenser microphone system",
    "production_use": "Interior dialogue, boom, studio dialogue",
    "replacement_value_usd": 2300,
    "rental_day_rate_usd": 75,
    "voltage": "48 V phantom",
    "power_connector": "XLR",
    "battery_type": "N/A",
    "weight_kg": 0.13,
    "dimensions": "Mic varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Boom Mics",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://schoeps.de/en/products/colette/microphone-amplifiers/cmc-6.html",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0033",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=DPA+6060",
    "name": "DPA 6060 Lavalier",
    "category": "Audio",
    "subcategory": "Lavalier Microphone",
    "brand": "DPA",
    "model": "6060",
    "description": "Subminiature lavalier microphone",
    "production_use": "Talent lav for commercials and interviews",
    "replacement_value_usd": 675,
    "rental_day_rate_usd": 35,
    "voltage": "Bias power",
    "power_connector": "MicroDot / adapter",
    "battery_type": "N/A",
    "weight_kg": 0.01,
    "dimensions": "Subminiature",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Lavaliers",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.dpamicrophones.com/lavalier/6060-series-subminiature-lavalier-microphone/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0034",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Lectrosonics+D+Squared",
    "name": "Lectrosonics D Squared Wireless Kit",
    "category": "Audio",
    "subcategory": "Wireless System",
    "brand": "Lectrosonics",
    "model": "D Squared",
    "description": "Digital wireless transmitter/receiver kit",
    "production_use": "Professional wireless talent audio",
    "replacement_value_usd": 4200,
    "rental_day_rate_usd": 160,
    "voltage": "Battery / DC",
    "wattage": "varies",
    "power_connector": "TA5 / DC",
    "battery_type": "AA / external",
    "weight_kg": 0.5,
    "dimensions": "Kit varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Wireless Audio",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.lectrosonics.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0035",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Wisycom+MCR54",
    "name": "Wisycom MCR54 Wireless Receiver",
    "category": "Audio",
    "subcategory": "Wireless Receiver",
    "brand": "Wisycom",
    "model": "MCR54",
    "description": "Four-channel true diversity wireless receiver",
    "production_use": "Compact bag wireless reception",
    "replacement_value_usd": 2700,
    "rental_day_rate_usd": 110,
    "voltage": "5-18 V DC",
    "wattage": "varies",
    "power_connector": "Hirose / slot",
    "battery_type": "External",
    "weight_kg": 0.25,
    "dimensions": "Receiver varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Wireless Audio",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://wisycom.com/usa/product/mcr54/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "AUD0036",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Tentacle+Sync+Sync+E+mkII",
    "name": "Tentacle Sync E mkII",
    "category": "Audio",
    "subcategory": "Timecode",
    "brand": "Tentacle Sync",
    "model": "Sync E mkII",
    "description": "Compact timecode generator",
    "production_use": "Camera/audio sync, multicam productions",
    "replacement_value_usd": 289,
    "rental_day_rate_usd": 20,
    "voltage": "USB-C charging",
    "power_connector": "3.5mm timecode",
    "battery_type": "Internal battery",
    "weight_kg": 0.03,
    "dimensions": "Small box",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Audio Cage",
    "kit_name": "Timecode",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://tentaclesync.com/sync-e",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "MON0037",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=SmallHD+Cine+7",
    "name": "SmallHD Cine 7",
    "category": "Monitoring",
    "subcategory": "On-Camera Monitor",
    "brand": "SmallHD",
    "model": "Cine 7",
    "description": "7-inch high-brightness on-camera monitor",
    "production_use": "Camera operator and focus monitoring",
    "replacement_value_usd": 1699,
    "rental_day_rate_usd": 75,
    "voltage": "7-34 V DC",
    "wattage": "~20 W",
    "power_connector": "2-pin LEMO",
    "battery_type": "Sony L-series / external",
    "weight_kg": 0.57,
    "dimensions": "7 in monitor",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Monitors",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://smallhd.com/products/cine-7",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "MON0038",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=SmallHD+Cine+24",
    "name": "SmallHD Cine 24",
    "category": "Monitoring",
    "subcategory": "Production Monitor",
    "brand": "SmallHD",
    "model": "Cine 24",
    "description": "24-inch 4K high-bright production monitor",
    "production_use": "Video village, DIT, director monitor",
    "replacement_value_usd": 9000,
    "rental_day_rate_usd": 300,
    "voltage": "100-240 V AC / DC",
    "wattage": "~175 W",
    "power_connector": "AC / 4-pin XLR",
    "battery_type": "V-Mount option",
    "weight_kg": 6.8,
    "dimensions": "24 in monitor",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Production Monitors",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://smallhd.com/products/cine-24",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "MON0039",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Atomos+Shogun+Ultra",
    "name": "Atomos Shogun Ultra",
    "category": "Monitoring",
    "subcategory": "Recorder Monitor",
    "brand": "Atomos",
    "model": "Shogun Ultra",
    "description": "7-inch HDR monitor recorder",
    "production_use": "Camera recording and monitoring",
    "replacement_value_usd": 1299,
    "rental_day_rate_usd": 60,
    "voltage": "Battery / DC",
    "wattage": "varies",
    "power_connector": "DC",
    "battery_type": "NP-F / DC",
    "weight_kg": 0.36,
    "dimensions": "7 in monitor",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Record Monitors",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.atomos.com/explore/shogun-ultra/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "VID0040",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Teradek+Bolt+6+XT+1500",
    "name": "Teradek Bolt 6 XT 1500",
    "category": "Video Transmission",
    "subcategory": "Wireless Video",
    "brand": "Teradek",
    "model": "Bolt 6 XT 1500",
    "description": "Zero-delay wireless video transmitter/receiver",
    "production_use": "Director monitor, handheld camera wireless feed",
    "replacement_value_usd": 5990,
    "rental_day_rate_usd": 250,
    "voltage": "6-28 V DC",
    "wattage": "varies",
    "power_connector": "2-pin LEMO",
    "battery_type": "V-Mount / Gold Mount",
    "weight_kg": 0.5,
    "dimensions": "Kit varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Video Village",
    "kit_name": "Wireless Video",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://teradek.com/products/bolt-6",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "VID0041",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Teradek+Serv+4K",
    "name": "Teradek Serv 4K",
    "category": "Video Transmission",
    "subcategory": "Streaming Encoder",
    "brand": "Teradek",
    "model": "Serv 4K",
    "description": "4K HDR wireless video streaming encoder",
    "production_use": "Client monitoring, remote video village",
    "replacement_value_usd": 2790,
    "rental_day_rate_usd": 125,
    "voltage": "6-28 V DC",
    "wattage": "varies",
    "power_connector": "2-pin LEMO / Ethernet",
    "battery_type": "External",
    "weight_kg": 0.5,
    "dimensions": "Encoder varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Video Village",
    "kit_name": "Streaming",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://teradek.com/products/serv-4k",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "DIT0042",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Blackmagic+Design+ATEM+Mini+Extreme+ISO",
    "name": "Blackmagic ATEM Mini Extreme ISO",
    "category": "DIT / Switching",
    "subcategory": "Switcher",
    "brand": "Blackmagic Design",
    "model": "ATEM Mini Extreme ISO",
    "description": "8-input live production switcher with ISO recording",
    "production_use": "Streaming, live commercial, multicam switching",
    "replacement_value_usd": 1295,
    "rental_day_rate_usd": 85,
    "voltage": "12 V DC",
    "wattage": "36 W",
    "amperage": "3 A",
    "power_connector": "DC barrel",
    "battery_type": "N/A",
    "weight_kg": 1.23,
    "dimensions": "Switcher varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "DIT Cart",
    "kit_name": "Switchers",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.blackmagicdesign.com/products/atemmini",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "DIT0043",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Blackmagic+Design+UltraStudio+4K+Mini",
    "name": "Blackmagic UltraStudio 4K Mini",
    "category": "DIT / Capture",
    "subcategory": "Capture Playback",
    "brand": "Blackmagic Design",
    "model": "UltraStudio 4K Mini",
    "description": "Thunderbolt 3 capture/playback interface",
    "production_use": "DIT capture, playback, video assist",
    "replacement_value_usd": 995,
    "rental_day_rate_usd": 65,
    "voltage": "12 V DC",
    "wattage": "36 W",
    "amperage": "3 A",
    "power_connector": "DC",
    "battery_type": "N/A",
    "weight_kg": 1.2,
    "dimensions": "Rack size",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "DIT Cart",
    "kit_name": "Capture",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.blackmagicdesign.com/products/ultrastudio",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "DIT0044",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Apple+MacBook+Pro+16-inch+M3+Max",
    "name": "Apple MacBook Pro 16 M3 Max",
    "category": "DIT / Computer",
    "subcategory": "Laptop",
    "brand": "Apple",
    "model": "MacBook Pro 16-inch M3 Max",
    "description": "High-performance production laptop",
    "production_use": "DIT, editing, playback, production management",
    "replacement_value_usd": 3999,
    "rental_day_rate_usd": 125,
    "voltage": "USB-C / MagSafe",
    "wattage": "varies",
    "power_connector": "USB-C / MagSafe",
    "battery_type": "Internal battery",
    "weight_kg": 2.16,
    "dimensions": "16 in laptop",
    "status": "Available",
    "condition": "Excellent",
    "warehouse_location": "DIT Cart",
    "kit_name": "Computers",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.apple.com/macbook-pro/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0045",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+40in+C-Stand+Kit",
    "name": "Matthews 40in C-Stand Kit",
    "category": "Grip",
    "subcategory": "Stand",
    "brand": "Matthews",
    "model": "40in C-Stand Kit",
    "description": "Century stand with grip head and arm",
    "production_use": "Lighting and flag support",
    "replacement_value_usd": 250,
    "rental_day_rate_usd": 15,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 7,
    "dimensions": "40 in stand",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Stands",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/collections/c-stands",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0046",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Avenger+Combo+Stand",
    "name": "Avenger Combo Stand",
    "category": "Grip",
    "subcategory": "Stand",
    "brand": "Avenger",
    "model": "Combo Stand",
    "description": "Heavy-duty lighting stand",
    "production_use": "Large fixtures and rigging support",
    "replacement_value_usd": 450,
    "rental_day_rate_usd": 25,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 8.5,
    "dimensions": "Stand varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Stands",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.avenger-grip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0047",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+Mombo+Combo+Stand",
    "name": "Matthews Mombo Combo Stand",
    "category": "Grip",
    "subcategory": "Stand",
    "brand": "Matthews",
    "model": "Mombo Combo Stand",
    "description": "Tall heavy-duty combo stand",
    "production_use": "Large light support, overhead rigs",
    "replacement_value_usd": 650,
    "rental_day_rate_usd": 35,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 15,
    "dimensions": "Tall stand",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Stands",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0048",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Dana+Dolly+Dana+Dolly+Kit",
    "name": "Dana Dolly Kit",
    "category": "Grip",
    "subcategory": "Camera Dolly",
    "brand": "Dana Dolly",
    "model": "Dana Dolly Kit",
    "description": "Portable camera dolly system",
    "production_use": "Tabletop and track dolly moves",
    "replacement_value_usd": 1800,
    "rental_day_rate_usd": 90,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 12,
    "dimensions": "Kit varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Camera Movement",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://danadolly.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0049",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=J.L.+Fisher+Model+10+Dolly",
    "name": "Fisher Model 10 Dolly",
    "category": "Grip",
    "subcategory": "Camera Dolly",
    "brand": "J.L. Fisher",
    "model": "Model 10 Dolly",
    "description": "Professional camera dolly",
    "production_use": "Studio and commercial camera movement",
    "replacement_value_usd": 28000,
    "rental_day_rate_usd": 550,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 185,
    "dimensions": "Dolly varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Camera Movement",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.jlfisher.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0050",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Sachtler+Video+18",
    "name": "Sachtler Video 18 Tripod System",
    "category": "Grip",
    "subcategory": "Tripod",
    "brand": "Sachtler",
    "model": "Video 18",
    "description": "Fluid head tripod system",
    "production_use": "Camera support for cinema and broadcast",
    "replacement_value_usd": 7600,
    "rental_day_rate_usd": 150,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 8,
    "dimensions": "Tripod varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Tripods",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.sachtler.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0051",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Honda+EU7000is",
    "name": "Honda EU7000is Generator",
    "category": "Power",
    "subcategory": "Generator",
    "brand": "Honda",
    "model": "EU7000is",
    "description": "Portable inverter generator",
    "production_use": "Location power for small lighting packages",
    "replacement_value_usd": 5500,
    "rental_day_rate_usd": 150,
    "voltage": "120/240 V AC",
    "wattage": "7000 W peak",
    "amperage": "varies",
    "power_connector": "NEMA outlets",
    "battery_type": "N/A",
    "weight_kg": 118,
    "dimensions": "Generator",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Generators",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://powerequipment.honda.com/generators/models/eu7000is",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0052",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=EcoFlow+DELTA+Pro",
    "name": "EcoFlow DELTA Pro",
    "category": "Power",
    "subcategory": "Battery Power Station",
    "brand": "EcoFlow",
    "model": "DELTA Pro",
    "description": "Portable battery power station",
    "production_use": "Silent location power, data/video village",
    "replacement_value_usd": 3699,
    "rental_day_rate_usd": 125,
    "voltage": "120 V AC / DC",
    "wattage": "3600 W output",
    "amperage": "30 A max",
    "power_connector": "AC / DC / USB",
    "battery_type": "Internal battery",
    "weight_kg": 45,
    "dimensions": "Power station",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Battery Power",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.ecoflow.com/us/delta-pro-portable-power-station",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0053",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Bebob+V290RM",
    "name": "Bebob V290RM Cine Battery",
    "category": "Power",
    "subcategory": "Camera Battery",
    "brand": "Bebob",
    "model": "V290RM",
    "description": "High-capacity V-mount battery",
    "production_use": "Camera and monitor power",
    "replacement_value_usd": 550,
    "rental_day_rate_usd": 30,
    "voltage": "14.4 V",
    "wattage": "290 Wh",
    "power_connector": "V-Mount / D-Tap",
    "battery_type": "V-Mount",
    "weight_kg": 1.45,
    "dimensions": "Battery",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Battery Room",
    "kit_name": "V-Mount Batteries",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://bebob.de/en/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0054",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Core+SWX+Helix+Max+360",
    "name": "Core SWX Helix Max 360",
    "category": "Power",
    "subcategory": "Camera Battery",
    "brand": "Core SWX",
    "model": "Helix Max 360",
    "description": "High-voltage capable cinema battery",
    "production_use": "High-draw cinema cameras and accessories",
    "replacement_value_usd": 825,
    "rental_day_rate_usd": 40,
    "voltage": "14.8/28 V",
    "wattage": "360 Wh",
    "power_connector": "V-Mount / D-Tap / XLR",
    "battery_type": "V-Mount",
    "weight_kg": 1.8,
    "dimensions": "Battery",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Battery Room",
    "kit_name": "High Voltage Batteries",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://coreswx.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "DRN0055",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=DJI+Inspire+3",
    "name": "DJI Inspire 3 Combo",
    "category": "Drone",
    "subcategory": "Cinema Drone",
    "brand": "DJI",
    "model": "Inspire 3",
    "description": "Full-frame 8K cinema drone platform",
    "production_use": "Aerial commercials, cinema drone work",
    "replacement_value_usd": 16499,
    "rental_day_rate_usd": 650,
    "voltage": "Battery system",
    "power_connector": "TB51 battery",
    "battery_type": "TB51",
    "weight_kg": 4,
    "dimensions": "Aircraft varies",
    "status": "Available",
    "condition": "Excellent",
    "warehouse_location": "Drone Case",
    "kit_name": "Drones",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.dji.com/inspire-3",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "DRN0056",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=DJI+Mavic+3+Pro+Cine",
    "name": "DJI Mavic 3 Pro Cine",
    "category": "Drone",
    "subcategory": "Compact Drone",
    "brand": "DJI",
    "model": "Mavic 3 Pro Cine",
    "description": "Compact triple-camera cine drone",
    "production_use": "Travel, location scout, light commercial aerials",
    "replacement_value_usd": 4799,
    "rental_day_rate_usd": 200,
    "voltage": "Battery system",
    "power_connector": "Intelligent Flight Battery",
    "battery_type": "DJI battery",
    "weight_kg": 0.96,
    "dimensions": "Aircraft varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Drone Case",
    "kit_name": "Drones",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 90,
    "source_url": "https://www.dji.com/mavic-3-pro",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0057",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+LPL+to+PL+Adapter",
    "name": "ARRI LPL to PL Adapter",
    "category": "Accessories",
    "subcategory": "Lens Adapter",
    "brand": "ARRI",
    "model": "LPL to PL Adapter",
    "description": "Lens mount adapter for PL lenses on LPL cameras",
    "production_use": "Camera package accessory",
    "replacement_value_usd": 1700,
    "rental_day_rate_usd": 55,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.3,
    "dimensions": "Adapter",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Adapters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.arri.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0058",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Tilta+Nucleus-M",
    "name": "Tilta Nucleus-M Wireless Follow Focus",
    "category": "Accessories",
    "subcategory": "Follow Focus",
    "brand": "Tilta",
    "model": "Nucleus-M",
    "description": "Wireless lens control system",
    "production_use": "Focus/iris/zoom control",
    "replacement_value_usd": 1399,
    "rental_day_rate_usd": 75,
    "voltage": "Battery / D-Tap",
    "wattage": "varies",
    "power_connector": "D-Tap / battery",
    "battery_type": "18650 / external",
    "weight_kg": 2,
    "dimensions": "Kit varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Follow Focus",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://tilta.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0059",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Preston+Cinema+Systems+MDR-4",
    "name": "Preston MDR-4 Kit",
    "category": "Accessories",
    "subcategory": "Follow Focus",
    "brand": "Preston Cinema Systems",
    "model": "MDR-4",
    "description": "Professional wireless lens control system",
    "production_use": "Focus/iris/zoom control for cinema sets",
    "replacement_value_usd": 11500,
    "rental_day_rate_usd": 300,
    "voltage": "12-30 V DC",
    "wattage": "varies",
    "power_connector": "3-pin Fischer / LEMO",
    "battery_type": "External",
    "weight_kg": 2,
    "dimensions": "Kit varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Follow Focus",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://prestoncinema.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0060",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=OConnor+2575D",
    "name": "OConnor 2575D Fluid Head",
    "category": "Accessories",
    "subcategory": "Fluid Head",
    "brand": "OConnor",
    "model": "2575D",
    "description": "Heavy-duty cinema fluid head",
    "production_use": "Large camera support",
    "replacement_value_usd": 15000,
    "rental_day_rate_usd": 300,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 10.4,
    "dimensions": "Head varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Fluid Heads",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.ocon.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0061",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Tiffen+Black+Pro-Mist+1%2F8",
    "name": "Tiffen Black Pro-Mist 1/8 4x5.65",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Tiffen",
    "model": "Black Pro-Mist 1/8",
    "description": "Diffusion filter",
    "production_use": "Skin softening and highlight bloom",
    "replacement_value_usd": 450,
    "rental_day_rate_usd": 25,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://tiffen.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0062",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Schneider+Hollywood+Black+Magic+1%2F4",
    "name": "Schneider Hollywood Black Magic 1/4 4x5.65",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Schneider",
    "model": "Hollywood Black Magic 1/4",
    "description": "Diffusion filter",
    "production_use": "Commercial beauty and narrative diffusion",
    "replacement_value_usd": 520,
    "rental_day_rate_usd": 30,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://schneiderkreuznach.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0063",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Bright+Tangerine+Misfit+Atom",
    "name": "Bright Tangerine Misfit Atom Matte Box",
    "category": "Accessories",
    "subcategory": "Matte Box",
    "brand": "Bright Tangerine",
    "model": "Misfit Atom",
    "description": "Lightweight matte box",
    "production_use": "Lens shading and filter support",
    "replacement_value_usd": 600,
    "rental_day_rate_usd": 35,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.3,
    "dimensions": "Matte box",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Matte Boxes",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.brighttangerine.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0064",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=ARRI+WCU-4",
    "name": "ARRI WCU-4",
    "category": "Accessories",
    "subcategory": "Wireless Lens Control",
    "brand": "ARRI",
    "model": "WCU-4",
    "description": "Wireless compact lens control unit",
    "production_use": "Focus pulling, lens mapping, camera control",
    "replacement_value_usd": 9500,
    "rental_day_rate_usd": 250,
    "voltage": "Battery",
    "wattage": "varies",
    "power_connector": "Battery charger",
    "battery_type": "Sony NP-FM500H",
    "weight_kg": 0.75,
    "dimensions": "Hand unit",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Camera Support",
    "kit_name": "Follow Focus",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.arri.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "COM0065",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Motorola+Solutions+CP200d",
    "name": "Motorola CP200d Radio",
    "category": "Communications",
    "subcategory": "Two-Way Radio",
    "brand": "Motorola Solutions",
    "model": "CP200d",
    "description": "Portable production radio",
    "production_use": "Crew communications",
    "replacement_value_usd": 450,
    "rental_day_rate_usd": 25,
    "voltage": "Battery / charger",
    "power_connector": "Charger",
    "battery_type": "Li-ion battery",
    "weight_kg": 0.4,
    "dimensions": "Radio",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Production Office",
    "kit_name": "Radios",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.motorolasolutions.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "COM0066",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Hollyland+Solidcom+C1+Pro+8S",
    "name": "Hollyland Solidcom C1 Pro 8S",
    "category": "Communications",
    "subcategory": "Intercom",
    "brand": "Hollyland",
    "model": "Solidcom C1 Pro 8S",
    "description": "Wireless intercom headset system",
    "production_use": "Production crew communication",
    "replacement_value_usd": 3499,
    "rental_day_rate_usd": 150,
    "voltage": "Battery / charging case",
    "power_connector": "USB-C / charging case",
    "battery_type": "Internal headset battery",
    "weight_kg": 3,
    "dimensions": "8-headset kit",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Video Village",
    "kit_name": "Intercom",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 180,
    "source_url": "https://www.hollyland.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0067",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Formatt-Hitech+Firecrest+0.3+ND",
    "name": "Firecrest 0.3 ND 4x5.65 Filter",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Formatt-Hitech",
    "model": "Firecrest 0.3 ND",
    "description": "Neutral density filter",
    "production_use": "Exposure control for cameras",
    "replacement_value_usd": 350,
    "rental_day_rate_usd": 20,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "ND Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://formatt-hitechusa.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0068",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Formatt-Hitech+Firecrest+0.6+ND",
    "name": "Firecrest 0.6 ND 4x5.65 Filter",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Formatt-Hitech",
    "model": "Firecrest 0.6 ND",
    "description": "Neutral density filter",
    "production_use": "Exposure control for cameras",
    "replacement_value_usd": 350,
    "rental_day_rate_usd": 20,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "ND Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://formatt-hitechusa.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0069",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Formatt-Hitech+Firecrest+0.9+ND",
    "name": "Firecrest 0.9 ND 4x5.65 Filter",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Formatt-Hitech",
    "model": "Firecrest 0.9 ND",
    "description": "Neutral density filter",
    "production_use": "Exposure control for cameras",
    "replacement_value_usd": 350,
    "rental_day_rate_usd": 20,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "ND Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://formatt-hitechusa.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0070",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Formatt-Hitech+Firecrest+1.2+ND",
    "name": "Firecrest 1.2 ND 4x5.65 Filter",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Formatt-Hitech",
    "model": "Firecrest 1.2 ND",
    "description": "Neutral density filter",
    "production_use": "Exposure control for cameras",
    "replacement_value_usd": 350,
    "rental_day_rate_usd": 20,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "ND Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://formatt-hitechusa.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0071",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Formatt-Hitech+Firecrest+1.5+ND",
    "name": "Firecrest 1.5 ND 4x5.65 Filter",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Formatt-Hitech",
    "model": "Firecrest 1.5 ND",
    "description": "Neutral density filter",
    "production_use": "Exposure control for cameras",
    "replacement_value_usd": 350,
    "rental_day_rate_usd": 20,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "ND Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://formatt-hitechusa.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "ACC0072",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Formatt-Hitech+Firecrest+1.8+ND",
    "name": "Firecrest 1.8 ND 4x5.65 Filter",
    "category": "Accessories",
    "subcategory": "Filter",
    "brand": "Formatt-Hitech",
    "model": "Firecrest 1.8 ND",
    "description": "Neutral density filter",
    "production_use": "Exposure control for cameras",
    "replacement_value_usd": 350,
    "rental_day_rate_usd": 20,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 0.1,
    "dimensions": "4x5.65",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Filter Case",
    "kit_name": "ND Filters",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://formatt-hitechusa.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0073",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+4x4+Solid",
    "name": "Matthews 4x4 Solid Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "4x4 Solid",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 120,
    "rental_day_rate_usd": 10,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0074",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+4x4+Single",
    "name": "Matthews 4x4 Single Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "4x4 Single",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 180,
    "rental_day_rate_usd": 13,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 1.5,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0075",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+4x4+Double",
    "name": "Matthews 4x4 Double Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "4x4 Double",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 240,
    "rental_day_rate_usd": 16,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 2,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0076",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+6x6+Solid",
    "name": "Matthews 6x6 Solid Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "6x6 Solid",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 300,
    "rental_day_rate_usd": 19,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 2.5,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0077",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+6x6+Single",
    "name": "Matthews 6x6 Single Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "6x6 Single",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 360,
    "rental_day_rate_usd": 22,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 3,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0078",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+8x8+Solid",
    "name": "Matthews 8x8 Solid Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "8x8 Solid",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 420,
    "rental_day_rate_usd": 25,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 3.5,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0079",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+8x8+Single",
    "name": "Matthews 8x8 Single Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "8x8 Single",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 480,
    "rental_day_rate_usd": 28,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 4,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0080",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+12x12+Solid",
    "name": "Matthews 12x12 Solid Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "12x12 Solid",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 540,
    "rental_day_rate_usd": 31,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 4.5,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0081",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+12x12+Single",
    "name": "Matthews 12x12 Single Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "12x12 Single",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 600,
    "rental_day_rate_usd": 34,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 5,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "GRP0082",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Matthews+20x20+Solid",
    "name": "Matthews 20x20 Solid Flag/Frame",
    "category": "Grip",
    "subcategory": "Flag / Frame",
    "brand": "Matthews",
    "model": "20x20 Solid",
    "description": "Grip flag or frame",
    "production_use": "Light control and shaping",
    "replacement_value_usd": 660,
    "rental_day_rate_usd": 37,
    "voltage": "N/A",
    "battery_type": "N/A",
    "weight_kg": 5.5,
    "dimensions": "Grip textile/frame",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Grip Truck",
    "kit_name": "Flags and Frames",
    "owner": "Company",
    "insurance_required": true,
    "maintenance_cycle_days": 365,
    "source_url": "https://www.msegrip.com/",
    "notes": "Verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0083",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+25+ft+Stinger",
    "name": "25 ft Stinger",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "25 ft Stinger",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0084",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+50+ft+Stinger",
    "name": "50 ft Stinger",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "50 ft Stinger",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0085",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+100+ft+Stinger",
    "name": "100 ft Stinger",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "100 ft Stinger",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0086",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+Stage+Pin+Cable+25+ft",
    "name": "Stage Pin Cable 25 ft",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "Stage Pin Cable 25 ft",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0087",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+Stage+Pin+Cable+50+ft",
    "name": "Stage Pin Cable 50 ft",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "Stage Pin Cable 50 ft",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0088",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+PowerCON+Cable+25+ft",
    "name": "PowerCON Cable 25 ft",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "PowerCON Cable 25 ft",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0089",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+4-pin+XLR+Cable+10+ft",
    "name": "4-pin XLR Cable 10 ft",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "4-pin XLR Cable 10 ft",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  },
  {
    "item_id": "PWR0090",
    "image_search_url": "https://www.google.com/search?tbm=isch&q=Generic+D-Tap+Splitter+Cable",
    "name": "D-Tap Splitter Cable",
    "category": "Power",
    "subcategory": "Cable",
    "brand": "Generic",
    "model": "D-Tap Splitter Cable",
    "description": "Production power cable",
    "production_use": "Power distribution and accessory connection",
    "replacement_value_usd": 50,
    "rental_day_rate_usd": 5,
    "voltage": "120 V AC / DC varies",
    "battery_type": "N/A",
    "weight_kg": 1,
    "dimensions": "Cable length varies",
    "status": "Available",
    "condition": "Good",
    "warehouse_location": "Power Cage",
    "kit_name": "Cables",
    "owner": "Company",
    "insurance_required": false,
    "maintenance_cycle_days": 365,
    "notes": "Generic item; verify",
    "data_confidence": "Starter estimate"
  }
];

export const CATALOG_CATEGORIES = [...new Set(EQUIPMENT_CATALOG.map(i => i.category))];
export const CATALOG_SUBCATEGORIES = [...new Set(EQUIPMENT_CATALOG.map(i => i.subcategory))];

export const CATALOG_STATUSES = ['Available', 'Reserved', 'Checked Out', 'In Repair', 'Lost', 'Retired'];
export const CATALOG_CONDITIONS = ['Excellent', 'Good', 'Fair', 'Needs Service', 'Damaged'];