export interface EquipmentItem {
  name: string;
  brand: string;
  model: string;
  category: string;
  subcategory: string;
}

export const EQUIPMENT_CATEGORIES = [
  'Cameras', 'Lenses', 'Audio', 'Lighting', 'Grip & Support',
  'Monitors & Recorders', 'Power', 'Data & Storage', 'Drones & Specialty', 'Post Production',
];

export const EQUIPMENT_DB: EquipmentItem[] = [
  // ── CAMERAS ──────────────────────────────────────────────────────────────
  { name: 'ALEXA 35', brand: 'ARRI', model: 'ALEXA 35', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'ALEXA Mini LF', brand: 'ARRI', model: 'ALEXA Mini LF', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'ALEXA Mini', brand: 'ARRI', model: 'ALEXA Mini', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'AMIRA', brand: 'ARRI', model: 'AMIRA', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'Venice 2', brand: 'Sony', model: 'Venice 2', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'Venice', brand: 'Sony', model: 'Venice', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'FX9', brand: 'Sony', model: 'PXW-FX9', category: 'Cameras', subcategory: 'Professional' },
  { name: 'FX6', brand: 'Sony', model: 'ILME-FX6', category: 'Cameras', subcategory: 'Professional' },
  { name: 'FX3', brand: 'Sony', model: 'ILME-FX3', category: 'Cameras', subcategory: 'Professional' },
  { name: 'A7S III', brand: 'Sony', model: 'ILCE-7SM3', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'A7 IV', brand: 'Sony', model: 'ILCE-7M4', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'EOS C70', brand: 'Canon', model: 'EOS C70', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'EOS C300 Mark III', brand: 'Canon', model: 'EOS C300 III', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'EOS C500 Mark II', brand: 'Canon', model: 'EOS C500 II', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'EOS R5', brand: 'Canon', model: 'EOS R5', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'EOS R6 Mark II', brand: 'Canon', model: 'EOS R6 II', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'Ursa Mini Pro 12K', brand: 'Blackmagic', model: 'Ursa Mini Pro 12K', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'Pocket Cinema 6K G2', brand: 'Blackmagic', model: 'BMPCC6K G2', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'Pocket Cinema 4K', brand: 'Blackmagic', model: 'BMPCC4K', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'Z9', brand: 'Nikon', model: 'Z9', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'Z8', brand: 'Nikon', model: 'Z8', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'GH6', brand: 'Panasonic', model: 'Lumix GH6', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'S5 II', brand: 'Panasonic', model: 'Lumix S5 II', category: 'Cameras', subcategory: 'Mirrorless' },
  { name: 'RED V-RAPTOR 8K', brand: 'RED', model: 'V-RAPTOR 8K VV', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'RED KOMODO 6K', brand: 'RED', model: 'KOMODO 6K', category: 'Cameras', subcategory: 'Cinema' },
  { name: 'RED MONSTRO 8K VV', brand: 'RED', model: 'MONSTRO 8K VV', category: 'Cameras', subcategory: 'Cinema' },

  // ── LENSES ───────────────────────────────────────────────────────────────
  { name: 'Master Prime 25mm T1.3', brand: 'ARRI / Zeiss', model: 'Master Prime 25mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Master Prime 35mm T1.3', brand: 'ARRI / Zeiss', model: 'Master Prime 35mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Master Prime 50mm T1.3', brand: 'ARRI / Zeiss', model: 'Master Prime 50mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Signature Prime 25mm T1.8', brand: 'ARRI', model: 'Signature Prime 25mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Signature Prime 40mm T1.8', brand: 'ARRI', model: 'Signature Prime 40mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Signature Zoom 16-32mm', brand: 'ARRI', model: 'Signature Zoom 16-32', category: 'Lenses', subcategory: 'Zoom' },
  { name: 'Otus 28mm T1.4', brand: 'Zeiss', model: 'Otus 28mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Otus 55mm T1.4', brand: 'Zeiss', model: 'Otus 55mm', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Milvus 21mm', brand: 'Zeiss', model: 'Milvus 21mm', category: 'Lenses', subcategory: 'Prime' },
  { name: '85mm f/1.4 Art', brand: 'Sigma', model: '85mm f/1.4 Art', category: 'Lenses', subcategory: 'Prime' },
  { name: '24-70mm f/2.8 Art', brand: 'Sigma', model: '24-70mm f/2.8 Art', category: 'Lenses', subcategory: 'Zoom' },
  { name: '70-200mm f/2.8 Art', brand: 'Sigma', model: '70-200mm f/2.8', category: 'Lenses', subcategory: 'Zoom' },
  { name: '14-24mm f/2.8 G Master', brand: 'Sony', model: 'SEL1424GM', category: 'Lenses', subcategory: 'Zoom' },
  { name: '24-70mm f/2.8 G Master', brand: 'Sony', model: 'SEL2470GM2', category: 'Lenses', subcategory: 'Zoom' },
  { name: '70-200mm f/2.8 G Master', brand: 'Sony', model: 'SEL70200GM2', category: 'Lenses', subcategory: 'Zoom' },
  { name: 'RF 24-70mm f/2.8 L', brand: 'Canon', model: 'RF 24-70mm f/2.8', category: 'Lenses', subcategory: 'Zoom' },
  { name: 'RF 50mm f/1.2 L', brand: 'Canon', model: 'RF 50mm f/1.2L', category: 'Lenses', subcategory: 'Prime' },
  { name: 'Anamorphic 40mm T2', brand: 'Atlas', model: 'Orion 40mm', category: 'Lenses', subcategory: 'Anamorphic' },
  { name: 'Anamorphic 65mm T2', brand: 'Atlas', model: 'Orion 65mm', category: 'Lenses', subcategory: 'Anamorphic' },

  // ── AUDIO ────────────────────────────────────────────────────────────────
  { name: 'Sound Devices 833', brand: 'Sound Devices', model: '833', category: 'Audio', subcategory: 'Recorder' },
  { name: 'Sound Devices 888', brand: 'Sound Devices', model: '888', category: 'Audio', subcategory: 'Recorder' },
  { name: 'Sound Devices MixPre-6 II', brand: 'Sound Devices', model: 'MixPre-6 II', category: 'Audio', subcategory: 'Recorder' },
  { name: 'Sound Devices MixPre-3 II', brand: 'Sound Devices', model: 'MixPre-3 II', category: 'Audio', subcategory: 'Recorder' },
  { name: 'Zoom F8n Pro', brand: 'Zoom', model: 'F8n Pro', category: 'Audio', subcategory: 'Recorder' },
  { name: 'Zoom F6', brand: 'Zoom', model: 'F6', category: 'Audio', subcategory: 'Recorder' },
  { name: 'Tascam DR-701D', brand: 'Tascam', model: 'DR-701D', category: 'Audio', subcategory: 'Recorder' },
  { name: 'MKH 416', brand: 'Sennheiser', model: 'MKH 416', category: 'Audio', subcategory: 'Shotgun Mic' },
  { name: 'MKH 50', brand: 'Sennheiser', model: 'MKH 50', category: 'Audio', subcategory: 'Shotgun Mic' },
  { name: 'MKH 60', brand: 'Sennheiser', model: 'MKH 60', category: 'Audio', subcategory: 'Shotgun Mic' },
  { name: 'NTG5', brand: 'RØDE', model: 'NTG5', category: 'Audio', subcategory: 'Shotgun Mic' },
  { name: 'VideoMic Pro+', brand: 'RØDE', model: 'VideoMic Pro+', category: 'Audio', subcategory: 'Camera Mic' },
  { name: 'Wireless GO II', brand: 'RØDE', model: 'Wireless GO II', category: 'Audio', subcategory: 'Wireless' },
  { name: 'EW 100 G4-ME2', brand: 'Sennheiser', model: 'EW 100 G4-ME2', category: 'Audio', subcategory: 'Wireless' },
  { name: 'EW-DP ME 2 Set', brand: 'Sennheiser', model: 'EW-DP ME 2', category: 'Audio', subcategory: 'Wireless' },
  { name: 'G3 Combo', brand: 'Sennheiser', model: 'EW 112P G3', category: 'Audio', subcategory: 'Wireless' },
  { name: 'UwMic9 Kit', brand: 'Comica', model: 'BoomX-D PRO', category: 'Audio', subcategory: 'Wireless' },
  { name: 'DPA 4063', brand: 'DPA', model: '4063', category: 'Audio', subcategory: 'Lavalier' },
  { name: 'Sanken COS-11D', brand: 'Sanken', model: 'COS-11D', category: 'Audio', subcategory: 'Lavalier' },
  { name: 'Boom Pole 3m', brand: 'K-Tek', model: 'KBAC75CCR', category: 'Audio', subcategory: 'Boom Pole' },
  { name: 'Boom Pole 5m', brand: 'K-Tek', model: 'KBAC9CCR', category: 'Audio', subcategory: 'Boom Pole' },
  { name: 'Blimp Windshield', brand: 'Rycote', model: 'Cyclone', category: 'Audio', subcategory: 'Accessories' },
  { name: 'Deadcat Windshield', brand: 'Rycote', model: 'Mini Windjammer', category: 'Audio', subcategory: 'Accessories' },

  // ── LIGHTING ─────────────────────────────────────────────────────────────
  { name: 'SkyPanel S60-C', brand: 'ARRI', model: 'SkyPanel S60-C', category: 'Lighting', subcategory: 'LED Panel' },
  { name: 'SkyPanel S30-C', brand: 'ARRI', model: 'SkyPanel S30-C', category: 'Lighting', subcategory: 'LED Panel' },
  { name: 'Orbiter', brand: 'ARRI', model: 'Orbiter', category: 'Lighting', subcategory: 'LED Point Source' },
  { name: 'Fresnel 1 Plus', brand: 'ARRI', model: 'Fresnel 1 Plus', category: 'Lighting', subcategory: 'Fresnel' },
  { name: 'Fresnel 5 Plus', brand: 'ARRI', model: 'Fresnel 5 Plus', category: 'Lighting', subcategory: 'Fresnel' },
  { name: 'Aputure 600d Pro', brand: 'Aputure', model: '600d Pro', category: 'Lighting', subcategory: 'LED' },
  { name: 'Aputure 300d II', brand: 'Aputure', model: '300d II', category: 'Lighting', subcategory: 'LED' },
  { name: 'Aputure 120d II', brand: 'Aputure', model: '120d II', category: 'Lighting', subcategory: 'LED' },
  { name: 'Aputure Amaran 100x', brand: 'Amaran', model: '100x', category: 'Lighting', subcategory: 'LED' },
  { name: 'Aputure Nova P300c', brand: 'Aputure', model: 'Nova P300c', category: 'Lighting', subcategory: 'LED Panel' },
  { name: 'Litepanels Gemini 2x1', brand: 'Litepanels', model: 'Gemini 2x1', category: 'Lighting', subcategory: 'LED Panel' },
  { name: 'Litepanels Astra 6x', brand: 'Litepanels', model: 'Astra 6x', category: 'Lighting', subcategory: 'LED Panel' },
  { name: 'Nanlux Evoke 900C', brand: 'Nanlux', model: 'Evoke 900C', category: 'Lighting', subcategory: 'LED' },
  { name: 'Nanlite FS-200', brand: 'Nanlite', model: 'FS-200', category: 'Lighting', subcategory: 'LED' },
  { name: 'Joker 400', brand: 'K5600', model: 'Joker 400', category: 'Lighting', subcategory: 'HMI' },
  { name: 'Joker 800', brand: 'K5600', model: 'Joker 800', category: 'Lighting', subcategory: 'HMI' },
  { name: 'Arri M18', brand: 'ARRI', model: 'M18', category: 'Lighting', subcategory: 'HMI' },
  { name: 'Kino Flo Diva-Lite 415', brand: 'Kino Flo', model: 'Diva-Lite 415', category: 'Lighting', subcategory: 'Fluorescent' },
  { name: 'Kino Flo Celeb 450', brand: 'Kino Flo', model: 'Celeb 450', category: 'Lighting', subcategory: 'LED' },
  { name: 'Quasar Science Q-LED', brand: 'Quasar Science', model: 'Q-LED 4', category: 'Lighting', subcategory: 'Tube Light' },
  { name: 'Astera AX1 PixelTube', brand: 'Astera', model: 'AX1 PixelTube', category: 'Lighting', subcategory: 'Tube Light' },
  { name: 'Astera Helios Tube', brand: 'Astera', model: 'Helios Tube', category: 'Lighting', subcategory: 'Tube Light' },

  // ── GRIP & SUPPORT ───────────────────────────────────────────────────────
  { name: 'OConnor 2575', brand: "O'Connor", model: '2575', category: 'Grip & Support', subcategory: 'Fluid Head' },
  { name: 'OConnor 515', brand: "O'Connor", model: '515', category: 'Grip & Support', subcategory: 'Fluid Head' },
  { name: 'Sachtler Aktiv 8', brand: 'Sachtler', model: 'Aktiv 8', category: 'Grip & Support', subcategory: 'Fluid Head' },
  { name: 'Sachtler FSB 8', brand: 'Sachtler', model: 'FSB 8', category: 'Grip & Support', subcategory: 'Fluid Head' },
  { name: 'Manfrotto MVH509A', brand: 'Manfrotto', model: 'MVH509A', category: 'Grip & Support', subcategory: 'Fluid Head' },
  { name: 'Ronin 4D-6K', brand: 'DJI', model: 'Ronin 4D-6K', category: 'Grip & Support', subcategory: 'Gimbal' },
  { name: 'Ronin S3 Pro', brand: 'DJI', model: 'RS 3 Pro', category: 'Grip & Support', subcategory: 'Gimbal' },
  { name: 'Crane 3S', brand: 'Zhiyun', model: 'Crane 3S', category: 'Grip & Support', subcategory: 'Gimbal' },
  { name: 'Weebill S', brand: 'Zhiyun', model: 'Weebill S', category: 'Grip & Support', subcategory: 'Gimbal' },
  { name: 'Steadicam Zephyr HD', brand: 'Tiffen', model: 'Zephyr HD', category: 'Grip & Support', subcategory: 'Steadicam' },
  { name: 'Syrp Genie Mini II', brand: 'Syrp', model: 'Genie Mini II', category: 'Grip & Support', subcategory: 'Motion Control' },
  { name: 'Dana Dolly', brand: 'Matthews', model: 'Dana Dolly', category: 'Grip & Support', subcategory: 'Dolly' },
  { name: 'Doorway Dolly', brand: 'Matthews', model: 'Doorway Dolly', category: 'Grip & Support', subcategory: 'Dolly' },
  { name: 'Slider 100cm', brand: 'Edelkrone', model: 'SliderPLUS v3', category: 'Grip & Support', subcategory: 'Slider' },
  { name: 'Slider 150cm', brand: 'Rhino', model: 'ROV Pro 24"', category: 'Grip & Support', subcategory: 'Slider' },
  { name: 'Matthews C-Stand 40"', brand: 'Matthews', model: 'C-Stand 40"', category: 'Grip & Support', subcategory: 'Stands' },
  { name: 'Avenger D600 Stand', brand: 'Avenger', model: 'D600', category: 'Grip & Support', subcategory: 'Stands' },
  { name: 'Lightweight Stand', brand: 'Manfrotto', model: '1052BAC', category: 'Grip & Support', subcategory: 'Stands' },
  { name: '4x4 Scrim Jim Frame', brand: 'Westcott', model: 'Scrim Jim 4x4', category: 'Grip & Support', subcategory: 'Diffusion' },
  { name: '6x6 Silk Diffusion', brand: 'Matthews', model: 'Silk 6x6', category: 'Grip & Support', subcategory: 'Diffusion' },
  { name: '4x4 Black Flag', brand: 'Matthews', model: 'Flag 4x4', category: 'Grip & Support', subcategory: 'Flags' },
  { name: 'Knuckle Arm', brand: 'Matthews', model: 'Knuckle Arm', category: 'Grip & Support', subcategory: 'Arms & Clamps' },

  // ── MONITORS & RECORDERS ─────────────────────────────────────────────────
  { name: 'SmallHD 702 Touch', brand: 'SmallHD', model: '702 Touch', category: 'Monitors & Recorders', subcategory: 'On-Camera Monitor' },
  { name: 'SmallHD INDIE 7', brand: 'SmallHD', model: 'INDIE 7', category: 'Monitors & Recorders', subcategory: 'Director Monitor' },
  { name: 'SmallHD Cine 13', brand: 'SmallHD', model: 'Cine 13', category: 'Monitors & Recorders', subcategory: 'Director Monitor' },
  { name: 'Atomos Sumo 19', brand: 'Atomos', model: 'Sumo 19"', category: 'Monitors & Recorders', subcategory: 'Monitor Recorder' },
  { name: 'Atomos Shogun 7', brand: 'Atomos', model: 'Shogun 7', category: 'Monitors & Recorders', subcategory: 'Monitor Recorder' },
  { name: 'Atomos Ninja V+', brand: 'Atomos', model: 'Ninja V+', category: 'Monitors & Recorders', subcategory: 'Monitor Recorder' },
  { name: 'Blackmagic Video Assist 12G', brand: 'Blackmagic', model: 'Video Assist 12G HDR', category: 'Monitors & Recorders', subcategory: 'Monitor Recorder' },
  { name: 'Convergent Design Odyssey 7Q+', brand: 'Convergent Design', model: 'Odyssey 7Q+', category: 'Monitors & Recorders', subcategory: 'Recorder' },
  { name: 'TVLogic F-5A', brand: 'TVLogic', model: 'F-5A', category: 'Monitors & Recorders', subcategory: 'Director Monitor' },
  { name: 'Lilliput 15.6" Monitor', brand: 'Lilliput', model: 'A15', category: 'Monitors & Recorders', subcategory: 'Director Monitor' },

  // ── POWER ────────────────────────────────────────────────────────────────
  { name: 'V-Mount Battery 150Wh', brand: 'Anton Bauer', model: 'Dionic 150', category: 'Power', subcategory: 'V-Mount Battery' },
  { name: 'V-Mount Battery 98Wh', brand: 'Hawk-Woods', model: 'VL-MK2', category: 'Power', subcategory: 'V-Mount Battery' },
  { name: 'Gold Mount Battery 160Wh', brand: 'Anton Bauer', model: 'Cine 150', category: 'Power', subcategory: 'Gold Mount Battery' },
  { name: 'NP-F970 Battery', brand: 'Sony', model: 'NP-F970', category: 'Power', subcategory: 'NP-F Battery' },
  { name: 'LP-E6NH Battery', brand: 'Canon', model: 'LP-E6NH', category: 'Power', subcategory: 'LP-E6 Battery' },
  { name: 'Quad V-Mount Charger', brand: 'Anton Bauer', model: 'P4 Quad', category: 'Power', subcategory: 'Charger' },
  { name: 'Power Station 1000Wh', brand: 'Jackery', model: 'Explorer 1000 Pro', category: 'Power', subcategory: 'Power Station' },
  { name: 'Power Distribution Box', brand: 'Lex', model: 'PD-8X20A', category: 'Power', subcategory: 'Distribution' },
  { name: 'Dimmer Board 6ch', brand: 'ETC', model: 'SmartPack 6ch', category: 'Power', subcategory: 'Dimmer' },
  { name: 'UPS 1500VA', brand: 'APC', model: 'BR1500G', category: 'Power', subcategory: 'UPS' },

  // ── DATA & STORAGE ───────────────────────────────────────────────────────
  { name: 'CFexpress Type B 512GB', brand: 'ProGrade', model: 'Cobalt 512GB', category: 'Data & Storage', subcategory: 'Memory Card' },
  { name: 'CFexpress Type B 256GB', brand: 'ProGrade', model: 'Cobalt 256GB', category: 'Data & Storage', subcategory: 'Memory Card' },
  { name: 'ARRI SXR Capture Drive 256GB', brand: 'ARRI', model: 'SXR 256GB', category: 'Data & Storage', subcategory: 'Memory Card' },
  { name: 'RED MINI-MAG 480GB', brand: 'RED', model: 'MINI-MAG 480GB', category: 'Data & Storage', subcategory: 'Memory Card' },
  { name: 'SxS Card 128GB', brand: 'Sony', model: 'SBP-128D', category: 'Data & Storage', subcategory: 'Memory Card' },
  { name: 'Thunderbolt SSD 2TB', brand: 'OWC', model: 'Envoy Pro FX', category: 'Data & Storage', subcategory: 'SSD' },
  { name: 'RAID 8TB', brand: 'G-Technology', model: 'G-RAID 2 8TB', category: 'Data & Storage', subcategory: 'RAID' },
  { name: 'Card Reader CFexpress', brand: 'ProGrade', model: 'PG05', category: 'Data & Storage', subcategory: 'Card Reader' },
  { name: 'DIT Cart Workstation', brand: 'Inovativ', model: 'Scout 37', category: 'Data & Storage', subcategory: 'DIT Cart' },
  { name: 'MacBook Pro 16" M3 Max', brand: 'Apple', model: 'MacBook Pro 16" M3 Max', category: 'Data & Storage', subcategory: 'Laptop' },

  // ── DRONES & SPECIALTY ───────────────────────────────────────────────────
  { name: 'DJI Inspire 3', brand: 'DJI', model: 'Inspire 3', category: 'Drones & Specialty', subcategory: 'Cinema Drone' },
  { name: 'DJI Mavic 3 Cine', brand: 'DJI', model: 'Mavic 3 Cine', category: 'Drones & Specialty', subcategory: 'Compact Drone' },
  { name: 'DJI Mini 4 Pro', brand: 'DJI', model: 'Mini 4 Pro', category: 'Drones & Specialty', subcategory: 'Compact Drone' },
  { name: 'GoPro Hero 12 Black', brand: 'GoPro', model: 'Hero 12 Black', category: 'Drones & Specialty', subcategory: 'Action Camera' },
  { name: 'Insta360 X4', brand: 'Insta360', model: 'X4', category: 'Drones & Specialty', subcategory: '360 Camera' },
  { name: 'Periscope Jib 12ft', brand: 'Losmandy', model: 'Chameleon Jib 12ft', category: 'Drones & Specialty', subcategory: 'Jib / Crane' },
  { name: 'MoVI Pro', brand: 'Freefly', model: 'MoVI Pro', category: 'Drones & Specialty', subcategory: 'Gimbal System' },
  { name: 'TERO Rover', brand: 'Freefly', model: 'TERO', category: 'Drones & Specialty', subcategory: 'Camera Car' },
  { name: 'Underwater Housing A7', brand: 'Ikelite', model: 'A7 Housing', category: 'Drones & Specialty', subcategory: 'Underwater' },
  { name: 'High Speed Phantom VEO', brand: 'Phantom', model: 'VEO4K 990', category: 'Drones & Specialty', subcategory: 'High Speed Camera' },

  // ── POST PRODUCTION ──────────────────────────────────────────────────────
  { name: 'Mac Pro M2 Ultra', brand: 'Apple', model: 'Mac Pro M2 Ultra', category: 'Post Production', subcategory: 'Workstation' },
  { name: 'Mac Studio M2 Ultra', brand: 'Apple', model: 'Mac Studio M2 Ultra', category: 'Post Production', subcategory: 'Workstation' },
  { name: 'DaVinci Resolve Panel Mini', brand: 'Blackmagic', model: 'DaVinci Mini Panel', category: 'Post Production', subcategory: 'Color Panel' },
  { name: 'DaVinci Resolve Panel Advanced', brand: 'Blackmagic', model: 'DaVinci Advanced Panel', category: 'Post Production', subcategory: 'Color Panel' },
  { name: 'Reference Monitor 4K', brand: 'Sony', model: 'BVM-HX310', category: 'Post Production', subcategory: 'Reference Monitor' },
  { name: 'UltraStudio 4K Mini', brand: 'Blackmagic', model: 'UltraStudio 4K Mini', category: 'Post Production', subcategory: 'Capture Card' },
  { name: 'Wacom Cintiq 27"', brand: 'Wacom', model: 'Cintiq Pro 27', category: 'Post Production', subcategory: 'Drawing Tablet' },
  { name: 'Avid S3 Control Surface', brand: 'Avid', model: 'S3', category: 'Post Production', subcategory: 'Audio Console' },
  { name: 'Genelec 8351B Studio Monitor', brand: 'Genelec', model: '8351B', category: 'Post Production', subcategory: 'Studio Monitor' },
  { name: 'Sony MDR-7506 Headphones', brand: 'Sony', model: 'MDR-7506', category: 'Post Production', subcategory: 'Headphones' },
];
